version: "3.8"


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auction-tcell
    ports:
      - '4000:4000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
