import type { Metadata } from "next";
import { Inter } from "next/font/google";
import BaseLayout from "@/components/Ui/Layouts/Base/BaseLayout";
import { getMessages, unstable_setRequestLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async  function RootLayout({
  children,
  params: {locale}
}: Readonly<{
  children: React.ReactNode;
  params: {locale: string};
}>) {
  
  unstable_setRequestLocale(locale);
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <head>
        <link rel="icon" href="/logo.svg" sizes="any" />
      </head>
      <body className={inter.className}>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <BaseLayout>
          {children}        
        </BaseLayout>
      </NextIntlClientProvider>
      </body>
    </html>
  );
}
