import type { Metadata } from "next";
import { Inter } from "next/font/google";
import BaseLayout from "@/components/Ui/Layouts/Base/BaseLayout";
import { getMessages, unstable_setRequestLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { useEffect, useState } from "react";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async  function RootLayout({
  children,
  params: {locale}
}: Readonly<{
  children: React.ReactNode;
  params: {locale: string};
}>) {
  
  unstable_setRequestLocale(locale);
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <head>
        <link rel="icon" href="/logo.svg" sizes="any" />
        <Script
          id="comfolks-script"
          dangerouslySetInnerHTML={{
            __html: `
              var s=document.createElement("script");s.type="text/javascript";s.async=true;
              s.src="https://api.comfolks.com/install.js?cf_api_key=A5yTs7tr";
              var x=document.getElementsByTagName("head")[0];x.appendChild(s);
            `,
          }}
        />
      </head>
      <body className={inter.className}>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <BaseLayout>
          {children}        
        </BaseLayout>
      </NextIntlClientProvider>
      </body>
    </html>
  );
}
