import type { Metadata } from "next";
import { Inter } from "next/font/google";
import BaseLayout from "@/components/Ui/Layouts/Base/BaseLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: {locale}
}: Readonly<{
  children: React.ReactNode;
  params: {locale: string};
}>) {
  return (
    <html lang={locale}>
      <head>
        <link rel="icon" href="/logo.svg" sizes="any" />
      </head>
      <body className={inter.className}>
        <BaseLayout>
          {children}        
        </BaseLayout>
      </body>
    </html>
  );
}
